spring.application.name=backend

#db config
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa config
spring.jpa.hibernate.ddl-auto=validate

# jwt access config
jwt.secret=${JWT_SECRET}
jwt.issuer=social.backend
jwt.access-token-ttl=PT15M

# refresh token config
auth.refresh-token-ttl=P30D
auth.refresh-token-bytes=32