create table users (
    id bigint primary key generated by default as identity,
    username varchar(255) not null unique,
    email varchar(255) not null,
    user_role varchar(255) not null default 'USER',
    phone_number varchar(255),
    first_name varchar(255),
    last_name varchar(255),
    password_hash varchar(255) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()

);

alter table users add constraint check_user_role check (user_role in ('USER', 'ADMIN'));
create unique index idx_users_email on users (lower(email));