create table sessions (
    id bigint primary key generated by default as identity,
    user_id bigint not null references users(id) on delete cascade,
    ip_address varchar(255),
    user_agent varchar(255),
    is_active boolean not null default true,
    expires_at timestamptz not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index idx_sessions_user_id on sessions (user_id);