create table refresh_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    session_id bigint not null references sessions(id) on delete cascade,
    hashed_token text not null unique,
    is_revoked boolean not null default false,
    used_at timestamptz,
    replaced_by bigint references refresh_tokens(id),
    expires_at timestamptz not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index idx_refresh_tokens_user_id on refresh_tokens(user_id);
create index idx_refresh_tokens_session_id on refresh_tokens(session_id);
create index idx_refresh_tokens_expires_at on refresh_tokens(expires_at);
create index idx_refresh_tokens_revoked on refresh_tokens(is_revoked);
